{{- $aliases := .Values.gateway.aliases | default (list) }}
{{- if $aliases }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.name }}-canonical-redirect
  labels:
    app: {{ .Values.name }}
spec:
  parentRefs:
{{- range $index, $_ := $aliases }}
    - name: {{ $.Values.name }}
      sectionName: https-{{ add $index 1 }}
{{- end }}

  hostnames:
{{- range $aliases }}
    - {{ . | quote }}
{{- end }}

  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            hostname: {{ .Values.gateway.hostname | quote }}
            statusCode: 301
{{- end }}
