name: tu-historia-en-papel-frontend

replicaCount: 1
deploymentSha: ""

image:
  repository: ghcr.io/romeronet/tu-historia-en-papel-frontend/node
  tag: latest
  pullPolicy: Always

service:
  port: 8080

gateway:
  className: traefik
  controllerName: traefik.io/gateway-controller
  hostname: tuhistoriaenpapel.com
  clusterIssuer: letsencrypt-prod
  tlsSecretName: app-tls
