name: tu-historia-en-papel-frontend

replicaCount: 1
deploymentSha: ""

image:
  repository: ghcr.io/romeronet/tu-historia-en-papel-frontend/node
  tag: latest
  pullPolicy: Always

service:
  port: 8080

smtp:
  secretName: tu-historia-en-papel-frontend-smtp

siteUrl: https://creahistoriastudio.com

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 256Mi

gateway:
  className: traefik
  hostname: creahistoriastudio.com
  aliases:
    - www.creahistoriastudio.com
    - tuhistoriaenpapel.com
  clusterIssuer: letsencrypt-prod
  tlsSecretName: app-tls
